# Generated by Django 3.2.8 on 2021-11-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
